//! Dependency-free CSS parsing and selector primitives.
#[derive(Clone,Debug,Default)] pub struct Stylesheet { pub rules:Vec<Rule> }
#[derive(Clone,Debug)] pub struct Rule { pub selector:String, pub declarations:Vec<Declaration>, pub order:usize }
#[derive(Clone,Debug)] pub struct Declaration { pub property:String, pub value:String, pub important:bool }
pub fn parse(input:&str)->Stylesheet { let s=strip_comments(input); let mut out=Stylesheet::default(); let mut p=0; while let Some(i)=s[p..].find('{'){let i=p+i;let Some(j)=s[i+1..].find('}')else{break};let j=i+1+j;let d=parse_declarations(&s[i+1..j]);for q in s[p..i].split(',').map(str::trim).filter(|x|!x.is_empty()){out.rules.push(Rule{selector:q.into(),declarations:d.clone(),order:out.rules.len()});}p=j+1;}out }
pub fn parse_declarations(s:&str)->Vec<Declaration>{s.split(';').filter_map(|x|x.find(':').map(|i|(x,i))).filter_map(|(x,i)|{let property=x[..i].trim().to_ascii_lowercase();let mut value=x[i+1..].trim().to_string();if property.is_empty()||value.is_empty(){return None}let important=value.to_ascii_lowercase().ends_with("!important");if important{value.truncate(value.len()-10);value=value.trim().into()}Some(Declaration{property,value,important})}).collect()}
fn strip_comments(s:&str)->String{let mut r=String::new();let mut i=0;while i<s.len(){if s[i..].starts_with("/*"){i+=2;while i+1<s.len()&&!s[i..].starts_with("*/"){i+=1}i=(i+2).min(s.len())}else{r.push(s.as_bytes()[i]as char);i+=1}}r}
pub fn specificity(s:&str)->(u32,u32,u32){let mut r=(0,0,0);for t in s.split(|c|c==' '||c=='>'){r.0+=t.matches('#').count()as u32;r.1+=(t.matches('.').count()+t.matches('[').count())as u32;if t.chars().next().map(|c|c.is_alphabetic()).unwrap_or(false){r.2+=1}}r}
#[cfg(test)]mod tests{use super::*;#[test]fn parse_css(){let x=parse("/*x*/p{color:red;width:2px!important}");assert_eq!(x.rules.len(),1);assert!(x.rules[0].declarations[1].important)}#[test]fn specificity(){assert_eq!(specificity("#a.x p"),(1,1,1));}}
