//! Forgiving, dependency-free HTML parser.
use crate::dom::{Document,Node,NodeKind};

fn parse_attrs(s:&str)->(String, std::collections::BTreeMap<String,String>) {
 let mut i=0; while i<s.len() && !s.as_bytes()[i].is_ascii_whitespace(){i+=1} let name=s[..i].to_ascii_lowercase(); let mut a=std::collections::BTreeMap::new();
 while i<s.len(){while i<s.len()&&s.as_bytes()[i].is_ascii_whitespace(){i+=1} if i>=s.len(){break} let st=i; while i<s.len()&&!s.as_bytes()[i].is_ascii_whitespace()&&s.as_bytes()[i]!=b'=' {i+=1} let k=s[st..i].to_ascii_lowercase(); while i<s.len()&&s.as_bytes()[i].is_ascii_whitespace(){i+=1} let mut v=String::new(); if i<s.len()&&s.as_bytes()[i]==b'=' {i+=1;while i<s.len()&&s.as_bytes()[i].is_ascii_whitespace(){i+=1} if i<s.len()&&(s.as_bytes()[i]==b'"'||s.as_bytes()[i]==b'\''){let q=s.as_bytes()[i];i+=1;let st=i;while i<s.len()&&s.as_bytes()[i]!=q{i+=1}v=s[st..i].to_string();if i<s.len(){i+=1}}else{let st=i;while i<s.len()&&!s.as_bytes()[i].is_ascii_whitespace(){i+=1}v=s[st..i].to_string()}} if !k.is_empty(){a.insert(k,v)} }
 (name,a)
}
pub fn parse(input:&str)->Document { let mut root=Node::element("document"); let mut stack:Vec<Node>=Vec::new(); let mut rest=input; let raw_tags=["script","style"]; while !rest.is_empty(){ if let Some(p)=rest.find('<'){if p>0{let t=&rest[..p];if !t.is_empty(){stack.last_mut().unwrap_or(&mut root).append_child(Node::text(t));}rest=&rest[p..];} else { if rest.starts_with("<!--"){if let Some(e)=rest.find("-->"){stack.last_mut().unwrap_or(&mut root).children.push(Node{ id:crate::model::NodeId(0),kind:NodeKind::Comment(rest[4..e].into()),attributes:Default::default(),children:vec![]});rest=&rest[e+3..];continue}else{break}} if let Some(e)=rest.find('>'){let inside=&rest[1..e]; if inside.starts_with('/') {let tag=inside[1..].trim().to_ascii_lowercase(); if let Some(pos)=stack.iter().rposition(|n|n.tag_name()==Some(tag.as_str())){while stack.len()>pos{let n=stack.pop().unwrap();stack.last_mut().unwrap_or(&mut root).append_child(n)}}} else if inside.starts_with('!'){ } else {let (tag,attrs)=parse_attrs(inside.trim_end_matches('/')); if !tag.is_empty(){let mut n=Node::element(&tag);n.attributes=attrs;let selfclose=inside.trim_end().ends_with('/')||["br","img","meta","link","input","hr","area","base","embed","source","wbr"].contains(&tag.as_str()); if selfclose{stack.last_mut().unwrap_or(&mut root).append_child(n)}else{stack.push(n); if raw_tags.contains(&tag.as_str()){if let Some(x)=rest[e+1..].to_ascii_lowercase().find(&format!("</{}",tag)){let body=&rest[e+1..e+1+x];stack.last_mut().unwrap().append_child(Node::text(body));rest=&rest[e+1+x..];continue}}}}}rest=&rest[e+1..];}else{stack.last_mut().unwrap_or(&mut root).append_child(Node::text(rest));break}}}else{stack.last_mut().unwrap_or(&mut root).append_child(Node::text(rest));break}} while let Some(n)=stack.pop(){stack.last_mut().unwrap_or(&mut root).append_child(n)} Document{root} }
#[cfg(test)] mod tests { use super::*; #[test] fn nesting_attributes_and_raw(){let d=parse("<div id=x><p>A<b>B</div><script>a < b</script>");assert_eq!(d.get_element_by_id("x").unwrap().text(),"AB");assert_eq!(d.root.find_by_tag("script")[0].text(),"a < b");} }
